services:
  # A Docker web service
  - type: web
    name: pocketai
    env: docker
    repo: https://github.com/enablerdao/pocketai.git
    branch: main
    buildCommand: docker build -t pocketai .
    startCommand: docker run -p 54656:54656 -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY pocketai
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /
    numInstances: 1
    plan: free